//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.Pegh.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.Pegh.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A secret has been enhanced, &apos;{0}&apos; is not found in &quot;{1}&quot;, copy it from &quot;{2}&quot; and adjust it.
        /// </summary>
        internal static string AddedPropertyNotFoundInLoadedSecret {
            get {
                return ResourceManager.GetString("AddedPropertyNotFoundInLoadedSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to create a log entry without a scope. Use BeginScope&lt;&gt;, and on the same thread.
        /// </summary>
        internal static string AttemptToLogWithoutScope {
            get {
                return ResourceManager.GetString("AttemptToLogWithoutScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call stack is too small to extract a creator method.
        /// </summary>
        internal static string CallStackTooSmallToFindCreatorMethodName {
            get {
                return ResourceManager.GetString("CallStackTooSmallToFindCreatorMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy &quot;{0}&quot; to &quot;{1}&quot;.
        /// </summary>
        internal static string FailedToCopy {
            get {
                return ResourceManager.GetString("FailedToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rename &quot;{0}&quot; into &quot;{1}&quot;.
        /// </summary>
        internal static string FailedToRename {
            get {
                return ResourceManager.GetString("FailedToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder placeholder {0} is not defined. Either define it as a machine drive in secret &quot;{1}&quot; or as a logical folder in secret &quot;{2}&quot;.
        /// </summary>
        internal static string FolderPlaceholderNotFound {
            get {
                return ResourceManager.GetString("FolderPlaceholderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder placeholders {0} are not defined. Either define them as machine drives in secret &quot;{1}&quot; or as logical folders in secret &quot;{2}&quot;.
        /// </summary>
        internal static string FolderPlaceholdersNotFound {
            get {
                return ResourceManager.GetString("FolderPlaceholdersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema &quot;{0}&quot; is invalid.
        /// </summary>
        internal static string InvalidSchema {
            get {
                return ResourceManager.GetString("InvalidSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not valid according to &quot;{1}&quot; ({2}).
        /// </summary>
        internal static string InvalidXml {
            get {
                return ResourceManager.GetString("InvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A secret has not been defined. Please load sample &quot;{0}&quot;, adjust and then save as &quot;{1}&quot;.
        /// </summary>
        internal static string PleaseLoadSecretSampleAdjustAndThenSaveAs {
            get {
                return ResourceManager.GetString("PleaseLoadSecretSampleAdjustAndThenSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scope exists, but it has not been created by the methods in the call stack.
        /// </summary>
        internal static string ScopeExistsButOutsideCallStack {
            get {
                return ResourceManager.GetString("ScopeExistsButOutsideCallStack", resourceCulture);
            }
        }
    }
}
